apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "zeebe-http-worker.fullname" . }}
  labels:
    app: {{ include "zeebe-http-worker.name" . }}
    chart: {{ include "zeebe-http-worker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "zeebe-http-worker.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "zeebe-http-worker.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.run }}
{{ toYaml .Values.run | indent 10 -}}
{{- end }}
          env:
          - name: zeebe.client.broker.contactPoint
            value: "{{ .Values.zeebeBrokerUrl }}"
          ports:
            - name: http
              containerPort: {{ default 80 .Values.service.internalPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{ default "/actuator/health" .Values.readinessProbe.probePath }}
              port: http
            initialDelaySeconds: {{ default 30 .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 15 .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ default "/actuator/health" .Values.livenessProbe.probePath }}
              port: http
            initialDelaySeconds: {{ default 30 .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 15 .Values.livenessProbe.periodSeconds }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
